package com.bdd.xpath;

public class ObtenerXpath {

    public static String buscadorDestino = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.compose.ui.platform.ComposeView/android.view.View/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.view.ViewGroup/android.widget.EditText";
    public static String  ingresoLogin ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.ScrollView/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.Button[1]";
    public static String seleccionarDestino ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.compose.ui.platform.ComposeView/android.view.View/android.view.ViewGroup/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/androidx.recyclerview.widget.RecyclerView/android.view.ViewGroup[1]";
    public static String seleccionarPersona ="//android.widget.Button[@content-desc='1 room, 2 adults, 0 children']";
    public static String seleecionarHotel ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.FrameLayout[2]/android.view.ViewGroup";
    public static String reservarHabitacion = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.View/android.view.View/android.widget.Button";
    public static String seleccionarEstancia ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.FrameLayout/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView/android.widget.LinearLayout[1]/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout[3]/android.widget.FrameLayout/android.view.ViewGroup/android.view.View/android.view.View/android.widget.Button";
    public static String reservarEstancia = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.Button";
    public static String mensajeSeleccionReserva = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.RelativeLayout/android.widget.LinearLayout[1]/android.widget.TextSwitcher/android.widget.TextView";

    public static String nombreDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_firstname_value']//*[@class='android.widget.EditText']";
    public static String apellidoDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_lastname_value']//*[@class='android.widget.EditText']";
    public static String mailDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_email_value']//*[@class='android.widget.EditText']";
    public static String direccionDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_address_value']//*[@class='android.widget.EditText']";
    public static String codigoPostalDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_zipcode_value']//*[@class='android.widget.EditText']";
    public static String ciudadlDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_city_value']//*[@class='android.widget.EditText']";
    public static String paisDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_country_value']//*[@class='android.widget.EditText']";
    public static String telefonoDatoReserva = "//*[@resource-id='com.booking:id/bstage1_contact_telephone_value']//*[@class='android.widget.EditText']";
    public static String siguienteInforPersonal ="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[2]/android.widget.LinearLayout/androidx.compose.ui.platform.ComposeView";
}
